### ISSUE TITLE
File system layout

### ISSUE THREAD

**Issue by mudler** [mudler/cOS#5]
By default, only the relevant dir for the container runtime should be writable.

We should have then:
- [x] read only `/usr` - `/` if feasable
- [x] ephemeral `/etc` that gets wiped out each time (tmpfs mount?)
- [x] persistency only on `/usr/local` and `/oem` folder

Mind also to switch back https://github.com/mudler/cOS/blob/31749456b54f3eb60ad203cd3f212c6717b29320/packages/initramfs/loader.sh#L225

Persistency partitions and `/etc/fstab` configuration can be driven by cloud-init config files, currently in https://github.com/mudler/cOS/blob/31749456b54f3eb60ad203cd3f212c6717b29320/packages/cloud-config/yipfiles/01_defaults.yaml#L12 and from the installation phase
Every user-side or oem configuration, will be handled by #4 and #24

## Action items:

- [x] Investigate layout from other projects on how they feased problematics regarding this topic
- [x] Configure the layout in the init, and cloud-config files
- [x] Modify installer to create a persistent partition (that occupy all the space left)
- [x] Tweak init to mount such partition
- [x] QA

~~Depends on #4~~ Merged

**Comment by davidcassany** [comment]
I did a search on MicroOS and the layout there looks like:

* `/etc` is an overlayfs on tmpfs
* `/` is a readonly mount
*  `root`, `/opt`, `/home`, `/usr/local` and `/srv` read/write btrfs subvolume
* `/var` read/write partition
*  Then some `boot` artifacts are read write too.

**Comment by mudler** [comment]
I'll close this as we merged #48 , if needed will file new issues for follow-ups
